import type { GlobalConfig } from 'payload';
import { revalidatePath } from 'next/cache';
import { canPublish } from './access';
import { DEFAULT_ABOUT_PAGE_CONTENT } from '../lib/about-page-content';

export const AboutPageContent: GlobalConfig = {
  slug: 'aboutPageContent',
  label: 'About Page Content',
  admin: {
    group: 'Konten Website',
    description: 'Edit teks halaman About. Simpan untuk menerbitkan perubahan; desain, foto, dan struktur halaman tetap.',
  },
  access: { read: () => true, update: canPublish },
  hooks: {
    afterChange: [
      () => {
        try {
          revalidatePath('/about', 'page');
        } catch {
          // Ignore outside Next.js request context (e.g. migrations or CLI)
        }
      },
    ],
  },
  fields: [
    {
      type: 'tabs',
      tabs: [
        {
          label: 'Hero & Pengantar',
          fields: [
            {
              name: 'heroTitle',
              label: 'Judul Utama',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.heroTitle,
              admin: { description: 'Pisahkan baris dengan Enter. Teks di antara **dua bintang** diberi aksen huruf miring toska.' },
            },
            {
              name: 'heroIntro',
              label: 'Paragraf Pengantar Hero',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.heroIntro,
              admin: { description: 'Gunakan {founderName} untuk menyisipkan nama pendiri. Teks di antara **dua bintang** tampil tebal.' },
            },
            {
              name: 'heroTagline',
              label: 'Tagline Hero',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.heroTagline,
            },
          ],
        },
        {
          label: 'Filosofi & Misi',
          fields: [
            {
              name: 'philosophyEyebrow',
              label: 'Label Filosofi (Eyebrow)',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.philosophyEyebrow,
            },
            {
              name: 'philosophyTitle',
              label: 'Judul Filosofi',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.philosophyTitle,
            },
            {
              name: 'philosophyText1',
              label: 'Paragraf Filosofi 1',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.philosophyText1,
              admin: { description: 'Teks di antara *satu bintang* tampil miring (italic).' },
            },
            {
              name: 'philosophyText2',
              label: 'Paragraf Filosofi 2',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.philosophyText2,
            },
            {
              name: 'philosophyMetricLabel',
              label: 'Label Spesifikasi Metrik',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.philosophyMetricLabel,
            },
            {
              name: 'philosophyMetricText',
              label: 'Teks Spesifikasi Metrik',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.philosophyMetricText,
            },
            {
              name: 'missionEyebrow',
              label: 'Label Misi (Eyebrow)',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.missionEyebrow,
            },
            {
              name: 'missionTitle',
              label: 'Judul Misi',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.missionTitle,
            },
            {
              name: 'missionText1',
              label: 'Paragraf Misi 1',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.missionText1,
            },
            {
              name: 'missionText2',
              label: 'Paragraf Misi 2',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.missionText2,
              admin: { description: 'Teks di antara **dua bintang** tampil tebal.' },
            },
            {
              name: 'missionAccountabilityLabel',
              label: 'Label Akuntabilitas Studio',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.missionAccountabilityLabel,
            },
            {
              name: 'missionAccountabilityText',
              label: 'Teks Akuntabilitas Studio',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.missionAccountabilityText,
            },
            {
              name: 'missionStudioTag',
              label: 'Label Tag Studio',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.missionStudioTag,
            },
            {
              name: 'missionEstTag',
              label: 'Label Tahun Berdiri',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.missionEstTag,
            },
          ],
        },
        {
          label: 'Empat Pilar Praktik',
          fields: [
            {
              name: 'pillarsEyebrow',
              label: 'Label Pilar (Eyebrow)',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillarsEyebrow,
            },
            {
              name: 'pillarsHeading',
              label: 'Judul Empat Pilar',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillarsHeading,
            },
            {
              name: 'pillarsSubtitle',
              label: 'Keterangan Pilar',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillarsSubtitle,
            },
            {
              name: 'pillar1Tag',
              label: 'Pilar 01 Tag',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar1Tag,
            },
            {
              name: 'pillar1Title',
              label: 'Pilar 01 Judul',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar1Title,
            },
            {
              name: 'pillar1Desc',
              label: 'Pilar 01 Deskripsi',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar1Desc,
            },
            {
              name: 'pillar2Tag',
              label: 'Pilar 02 Tag',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar2Tag,
            },
            {
              name: 'pillar2Title',
              label: 'Pilar 02 Judul',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar2Title,
            },
            {
              name: 'pillar2Desc',
              label: 'Pilar 02 Deskripsi',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar2Desc,
            },
            {
              name: 'pillar3Tag',
              label: 'Pilar 03 Tag',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar3Tag,
            },
            {
              name: 'pillar3Title',
              label: 'Pilar 03 Judul',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar3Title,
            },
            {
              name: 'pillar3Desc',
              label: 'Pilar 03 Deskripsi',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar3Desc,
            },
            {
              name: 'pillar4Tag',
              label: 'Pilar 04 Tag',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar4Tag,
            },
            {
              name: 'pillar4Title',
              label: 'Pilar 04 Judul',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar4Title,
            },
            {
              name: 'pillar4Desc',
              label: 'Pilar 04 Deskripsi',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.pillar4Desc,
            },
          ],
        },
        {
          label: 'Pendiri & Tim',
          fields: [
            {
              name: 'principalRole',
              label: 'Jabatan / Peran Pendiri',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.principalRole,
            },
            {
              name: 'principalName',
              label: 'Nama Pendiri',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.principalName,
            },
            {
              name: 'principalCredentials',
              label: 'Gelar / Subtitle Pendiri',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.principalCredentials,
            },
            {
              name: 'principalBio1',
              label: 'Biografi Pendiri Paragraf 1',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.principalBio1,
            },
            {
              name: 'principalBio2',
              label: 'Biografi Pendiri Paragraf 2',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.principalBio2,
            },
            {
              name: 'principalBadgeTitle',
              label: 'Label Badge Foto Pendiri',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.principalBadgeTitle,
            },
            {
              name: 'principalBadgeSubtitle',
              label: 'Subtitle Badge Foto Pendiri',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.principalBadgeSubtitle,
            },
            {
              name: 'principalInstagramLabel',
              label: 'Label Tautan Instagram Pendiri',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.principalInstagramLabel,
            },
            {
              name: 'principalFacebookLabel',
              label: 'Label Tautan Facebook Pendiri',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.principalFacebookLabel,
            },
            {
              name: 'teamEyebrow',
              label: 'Label Tim (Eyebrow)',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.teamEyebrow,
            },
            {
              name: 'teamHeading',
              label: 'Judul Kolektif Tim',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.teamHeading,
            },
            {
              name: 'teamIntro',
              label: 'Teks Pengantar Kolaborator Tim',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.teamIntro,
              admin: { description: 'Teks di antara **dua bintang** tampil tebal.' },
            },
          ],
        },
        {
          label: 'Unit Bisnis & Layanan',
          fields: [
            {
              name: 'entitiesEyebrow',
              label: 'Label Unit Bisnis (Eyebrow)',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.entitiesEyebrow,
            },
            {
              name: 'entitiesHeading',
              label: 'Judul Unit Bisnis',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.entitiesHeading,
            },
            {
              name: 'entitiesSubtitle',
              label: 'Keterangan Unit Bisnis',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.entitiesSubtitle,
            },
            {
              name: 'servicesEyebrow',
              label: 'Label Layanan (Eyebrow)',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.servicesEyebrow,
            },
            {
              name: 'servicesHeading',
              label: 'Judul Layanan Spesialisasi',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.servicesHeading,
            },
            {
              name: 'servicesSubtitle',
              label: 'Keterangan Layanan',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.servicesSubtitle,
            },
            {
              name: 'locationHeading',
              label: 'Judul Bagian Lokasi',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.locationHeading,
            },
            {
              name: 'locationOfficeTitle',
              label: 'Nama Kantor Pusat',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.locationOfficeTitle,
            },
            {
              name: 'locationAreasTitle',
              label: 'Nama Jangkauan Wilayah',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.locationAreasTitle,
            },
          ],
        },
        {
          label: 'Banner Konsultasi',
          fields: [
            {
              name: 'ctaEyebrow',
              label: 'Label Banner (Eyebrow)',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.ctaEyebrow,
            },
            {
              name: 'ctaHeading',
              label: 'Judul Banner Konsultasi',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.ctaHeading,
            },
            {
              name: 'ctaText',
              label: 'Deskripsi Banner Konsultasi',
              type: 'textarea',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.ctaText,
            },
            {
              name: 'ctaButtonLabel',
              label: 'Label Tombol CTA',
              type: 'text',
              required: true,
              defaultValue: DEFAULT_ABOUT_PAGE_CONTENT.ctaButtonLabel,
            },
          ],
        },
      ],
    },
  ],
};
