/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    portfolioCategories: PortfolioCategory;
    news: News;
    services: Service;
    awards: Award;
    competitions: Competition;
    media: Media;
    team: Team;
    brandLogos: BrandLogo;
    inquiries: Inquiry;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    portfolioCategories: PortfolioCategoriesSelect<false> | PortfolioCategoriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    brandLogos: BrandLogosSelect<false> | BrandLogosSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    homepageContent: HomepageContent;
    aboutPageContent: AboutPageContent;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepageContent: HomepageContentSelect<false> | HomepageContentSelect<true>;
    aboutPageContent: AboutPageContentSelect<false> | AboutPageContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Isi informasi utama, tambahkan foto, lalu simpan draf atau terbitkan sesuai hak akses Anda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Otomatis dari judul saat disimpan jika dikosongkan. Bisa diisi sendiri, misalnya rumah-tropis. Jangan ubah alamat yang sudah dibagikan.
   */
  slug: string;
  category: number | PortfolioCategory;
  location?: string | null;
  year?: string | null;
  /**
   * Pilih status sesuai kondisi proyek. Nilai lama tetap dipertahankan.
   */
  status?: string | null;
  shortIntro?: string | null;
  architectInCharge?: string | null;
  siteArea?: string | null;
  constructedArea?: string | null;
  stories?: string | null;
  description?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  /**
   * Utamakan unggah atau pilih foto di atas. Tautan ini dipakai hanya jika foto unggahan belum dipilih.
   */
  heroImageUrl?: string | null;
  /**
   * Tambahkan foto, lalu geser baris untuk mengatur urutannya. Keterangan foto boleh dikosongkan.
   */
  gallery?:
    | {
        image?: (number | null) | Media;
        /**
         * Utamakan unggah atau pilih foto di atas. Tautan ini dipakai hanya jika foto unggahan belum dipilih.
         */
        imageUrl?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Masukkan konten ini ke daftar pilihan di website.
   */
  featured?: boolean | null;
  /**
   * Angka lebih kecil tampil lebih awal.
   */
  order?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  legacyId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Kelompokkan proyek berdasarkan jenis bangunannya.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolioCategories".
 */
export interface PortfolioCategory {
  id: number;
  title: string;
  /**
   * Otomatis dari judul saat disimpan jika dikosongkan. Bisa diisi sendiri, misalnya rumah-tropis. Jangan ubah alamat yang sudah dibagikan.
   */
  slug: string;
  description: string;
  coverImage?: (number | null) | Media;
  /**
   * Utamakan unggah atau pilih foto di atas. Tautan ini dipakai hanya jika foto unggahan belum dipilih.
   */
  coverImageUrl?: string | null;
  /**
   * Angka lebih kecil tampil lebih awal.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Unggah foto maksimal 10 MB per berkas. Isi deskripsi gambar sebelum menyimpan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Jelaskan isi gambar secara singkat untuk pembaca layar.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Kelola kabar studio. Simpan draf untuk ditinjau sebelum diterbitkan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Otomatis dari judul saat disimpan jika dikosongkan. Bisa diisi sendiri, misalnya rumah-tropis. Jangan ubah alamat yang sudah dibagikan.
   */
  slug: string;
  /**
   * Contoh: 1 Oktober 2026.
   */
  date?: string | null;
  category?: string | null;
  author?: string | null;
  publishDate?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Utamakan unggah atau pilih foto di atas. Tautan ini dipakai hanya jika foto unggahan belum dipilih.
   */
  coverImageUrl?: string | null;
  excerpt: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Masukkan konten ini ke daftar pilihan di website.
   */
  featured?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Layanan aktif tampil di halaman Services.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: string;
  /**
   * Angka lebih kecil tampil lebih awal.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catat penghargaan yang diterima studio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  title: string;
  year: string;
  issuer: string;
  category: string;
  project: string;
  description: string;
  /**
   * Angka lebih kecil tampil lebih awal.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola gagasan desain dan pencapaian sayembara.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: number;
  title: string;
  year: string;
  achievement: string;
  organizer: string;
  location: string;
  description: string;
  /**
   * Angka lebih kecil tampil lebih awal.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola profil dan foto anggota studio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  roleTitle: string;
  portrait?: (number | null) | Media;
  /**
   * Utamakan unggah atau pilih foto di atas. Tautan ini dipakai hanya jika foto unggahan belum dipilih.
   */
  portraitUrl?: string | null;
  bio?: string | null;
  instagram?: string | null;
  /**
   * Angka lebih kecil tampil lebih awal.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Unggah logo, pilih kelompoknya, lalu aktifkan agar tampil di website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandLogos".
 */
export interface BrandLogo {
  id: number;
  name: string;
  group: 'client' | 'collaborator' | 'media';
  logo: number | Media;
  /**
   * Jika kosong, memakai deskripsi berkas atau nama mitra.
   */
  alt?: string | null;
  url?: string | null;
  /**
   * Angka lebih kecil tampil lebih awal.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pesan dari formulir kontak. Perbarui status dan gunakan catatan internal untuk tindak lanjut.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  fullName: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  status: 'new' | 'read' | 'replied' | 'archived';
  /**
   * Hanya untuk tim studio; tidak ditampilkan di website.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pemilik mengelola akun dan hak akses tim. Editor dapat menyimpan draf; admin dan pemilik dapat menerbitkan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'owner' | 'admin' | 'editor';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'portfolioCategories';
        value: number | PortfolioCategory;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'competitions';
        value: number | Competition;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'brandLogos';
        value: number | BrandLogo;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  location?: T;
  year?: T;
  status?: T;
  shortIntro?: T;
  architectInCharge?: T;
  siteArea?: T;
  constructedArea?: T;
  stories?: T;
  description?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  heroImage?: T;
  heroImageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        caption?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolioCategories_select".
 */
export interface PortfolioCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  coverImageUrl?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  category?: T;
  author?: T;
  publishDate?: T;
  coverImage?: T;
  coverImageUrl?: T;
  excerpt?: T;
  body?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  issuer?: T;
  category?: T;
  project?: T;
  description?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  achievement?: T;
  organizer?: T;
  location?: T;
  description?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  roleTitle?: T;
  portrait?: T;
  portraitUrl?: T;
  bio?: T;
  instagram?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandLogos_select".
 */
export interface BrandLogosSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  logo?: T;
  alt?: T;
  url?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Ubah identitas, kontak, media sosial dan logo studio. Pengaturan ini hanya dapat diubah oleh pemilik.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  established: string;
  founder: string;
  address: string;
  workingAreas: string;
  phone: string;
  email: string;
  instagram: string;
  instagramFounder: string;
  facebook: string;
  logo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit teks pengenalan studio di homepage. Simpan untuk menerbitkan perubahan; desain dan tautan tetap.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepageContent".
 */
export interface HomepageContent {
  id: number;
  eyebrow: string;
  services: string;
  headline: string;
  /**
   * Gunakan {founderName} untuk menyisipkan nama pendiri dari field di bawah. Teks di antara **dua bintang** tampil tebal.
   */
  leftParagraph: string;
  /**
   * Teks di antara **dua bintang** tampil tebal. HTML tidak digunakan.
   */
  rightParagraph: string;
  founderName: string;
  ctaLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit teks halaman About. Simpan untuk menerbitkan perubahan; desain, foto, dan struktur halaman tetap.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPageContent".
 */
export interface AboutPageContent {
  id: number;
  /**
   * Pisahkan baris dengan Enter. Teks di antara **dua bintang** diberi aksen huruf miring toska.
   */
  heroTitle: string;
  /**
   * Gunakan {founderName} untuk menyisipkan nama pendiri. Teks di antara **dua bintang** tampil tebal.
   */
  heroIntro: string;
  heroTagline: string;
  philosophyEyebrow: string;
  philosophyTitle: string;
  /**
   * Teks di antara *satu bintang* tampil miring (italic).
   */
  philosophyText1: string;
  philosophyText2: string;
  philosophyMetricLabel: string;
  philosophyMetricText: string;
  missionEyebrow: string;
  missionTitle: string;
  missionText1: string;
  /**
   * Teks di antara **dua bintang** tampil tebal.
   */
  missionText2: string;
  missionAccountabilityLabel: string;
  missionAccountabilityText: string;
  missionStudioTag: string;
  missionEstTag: string;
  pillarsEyebrow: string;
  pillarsHeading: string;
  pillarsSubtitle: string;
  pillar1Tag: string;
  pillar1Title: string;
  pillar1Desc: string;
  pillar2Tag: string;
  pillar2Title: string;
  pillar2Desc: string;
  pillar3Tag: string;
  pillar3Title: string;
  pillar3Desc: string;
  pillar4Tag: string;
  pillar4Title: string;
  pillar4Desc: string;
  principalRole: string;
  principalName: string;
  principalCredentials: string;
  principalBio1: string;
  principalBio2: string;
  principalBadgeTitle: string;
  principalBadgeSubtitle: string;
  principalInstagramLabel: string;
  principalFacebookLabel: string;
  teamEyebrow: string;
  teamHeading: string;
  /**
   * Teks di antara **dua bintang** tampil tebal.
   */
  teamIntro: string;
  entitiesEyebrow: string;
  entitiesHeading: string;
  entitiesSubtitle: string;
  servicesEyebrow: string;
  servicesHeading: string;
  servicesSubtitle: string;
  locationHeading: string;
  locationOfficeTitle: string;
  locationAreasTitle: string;
  ctaEyebrow: string;
  ctaHeading: string;
  ctaText: string;
  ctaButtonLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  established?: T;
  founder?: T;
  address?: T;
  workingAreas?: T;
  phone?: T;
  email?: T;
  instagram?: T;
  instagramFounder?: T;
  facebook?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepageContent_select".
 */
export interface HomepageContentSelect<T extends boolean = true> {
  eyebrow?: T;
  services?: T;
  headline?: T;
  leftParagraph?: T;
  rightParagraph?: T;
  founderName?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPageContent_select".
 */
export interface AboutPageContentSelect<T extends boolean = true> {
  heroTitle?: T;
  heroIntro?: T;
  heroTagline?: T;
  philosophyEyebrow?: T;
  philosophyTitle?: T;
  philosophyText1?: T;
  philosophyText2?: T;
  philosophyMetricLabel?: T;
  philosophyMetricText?: T;
  missionEyebrow?: T;
  missionTitle?: T;
  missionText1?: T;
  missionText2?: T;
  missionAccountabilityLabel?: T;
  missionAccountabilityText?: T;
  missionStudioTag?: T;
  missionEstTag?: T;
  pillarsEyebrow?: T;
  pillarsHeading?: T;
  pillarsSubtitle?: T;
  pillar1Tag?: T;
  pillar1Title?: T;
  pillar1Desc?: T;
  pillar2Tag?: T;
  pillar2Title?: T;
  pillar2Desc?: T;
  pillar3Tag?: T;
  pillar3Title?: T;
  pillar3Desc?: T;
  pillar4Tag?: T;
  pillar4Title?: T;
  pillar4Desc?: T;
  principalRole?: T;
  principalName?: T;
  principalCredentials?: T;
  principalBio1?: T;
  principalBio2?: T;
  principalBadgeTitle?: T;
  principalBadgeSubtitle?: T;
  principalInstagramLabel?: T;
  principalFacebookLabel?: T;
  teamEyebrow?: T;
  teamHeading?: T;
  teamIntro?: T;
  entitiesEyebrow?: T;
  entitiesHeading?: T;
  entitiesSubtitle?: T;
  servicesEyebrow?: T;
  servicesHeading?: T;
  servicesSubtitle?: T;
  locationHeading?: T;
  locationOfficeTitle?: T;
  locationAreasTitle?: T;
  ctaEyebrow?: T;
  ctaHeading?: T;
  ctaText?: T;
  ctaButtonLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}